// <auto-generated />
using System;
using FinalProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations
{
    [DbContext(typeof(LunchContext))]
    partial class LunchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardNo");

                    b.Property<string>("ChildFirstName");

                    b.Property<string>("ChildLasttName");

                    b.Property<int>("ItemId");

                    b.Property<string>("ItemName");

                    b.Property<int>("OrderId");

                    b.Property<int?>("ParentFamilyId");

                    b.Property<string>("PaymentTypeName");

                    b.Property<double>("Price");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<int>("Qty");

                    b.Property<int>("RoomNo");

                    b.Property<string>("TeacherName");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ParentFamilyId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FinalProject.Models.Menu", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InvoiceId");

                    b.Property<string>("ItemDescription");

                    b.Property<string>("ItemName")
                        .IsRequired();

                    b.Property<DateTime>("LunchDate");

                    b.Property<int?>("OrderId");

                    b.Property<int?>("PAdminSchoolId");

                    b.Property<double>("Price");

                    b.Property<string>("SchoolId");

                    b.HasKey("ItemId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PAdminSchoolId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("FinalProject.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardNo");

                    b.Property<string>("ChildFirstName");

                    b.Property<string>("ChildLasttName");

                    b.Property<int>("ItemId");

                    b.Property<string>("ItemName");

                    b.Property<int?>("ParentFamilyId");

                    b.Property<string>("PaymentTypeName");

                    b.Property<double>("Price");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<int>("Qty");

                    b.Property<int>("RoomNo");

                    b.Property<string>("TeacherName");

                    b.HasKey("OrderId");

                    b.HasIndex("ParentFamilyId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FinalProject.Models.PAdmin", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SchoolName")
                        .IsRequired();

                    b.HasKey("SchoolId");

                    b.ToTable("PAdmins");
                });

            modelBuilder.Entity("FinalProject.Models.Parent", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChildFirstName")
                        .IsRequired();

                    b.Property<string>("ChildLastName")
                        .IsRequired();

                    b.Property<int?>("PAdminSchoolId");

                    b.Property<string>("ParentName")
                        .IsRequired();

                    b.Property<int>("RoomNo");

                    b.Property<string>("SchoolName");

                    b.Property<string>("TeacherName")
                        .IsRequired();

                    b.HasKey("FamilyId");

                    b.HasIndex("PAdminSchoolId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("FinalProject.Models.Invoice", b =>
                {
                    b.HasOne("FinalProject.Models.Parent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentFamilyId");
                });

            modelBuilder.Entity("FinalProject.Models.Menu", b =>
                {
                    b.HasOne("FinalProject.Models.Invoice")
                        .WithMany("Menus")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("FinalProject.Models.Order")
                        .WithMany("Menus")
                        .HasForeignKey("OrderId");

                    b.HasOne("FinalProject.Models.PAdmin", "PAdmin")
                        .WithMany()
                        .HasForeignKey("PAdminSchoolId");
                });

            modelBuilder.Entity("FinalProject.Models.Order", b =>
                {
                    b.HasOne("FinalProject.Models.Parent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentFamilyId");
                });

            modelBuilder.Entity("FinalProject.Models.Parent", b =>
                {
                    b.HasOne("FinalProject.Models.PAdmin", "PAdmin")
                        .WithMany()
                        .HasForeignKey("PAdminSchoolId");
                });
#pragma warning restore 612, 618
        }
    }
}
